# Generated by Django 3.1.3 on 2021-06-05 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(default=0)),
                ('task_name', models.CharField(max_length=264)),
                ('task_priority', models.CharField(choices=[('انفجار', 'انفجار'), ('ESD', 'ESD'), ('normal stop', 'NORMAL STOP'), ('تاخیر در راه اندازی', 'تاخیر در راه اندازی'), ('موارد دیگر', 'موارد دیگر')], default='explosion', max_length=20)),
                ('task_responsible', models.CharField(choices=[('رئیس بهره بردار', 'رئیس بهره برداری'), ('سرپرست نوبتکارا', 'سرپرست نوبتکاران'), ('نوبتکار ارشد', 'نوبتکار ارشد'), ('نوبتکار', 'نوبتکار')], default='2', max_length=20)),
                ('task_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubTasks1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask1_id', models.IntegerField(default=1, unique=True)),
                ('subtask1_name', models.CharField(default='زیروظیفه', max_length=264, unique=True)),
                ('subtask1_priority', models.CharField(choices=[('انفجار', 'انفجار'), ('ESD', 'ESD'), ('normal stop', 'NORMAL STOP'), ('تاخیر در راه اندازی', 'تاخیر در راه اندازی'), ('موارد دیگر', 'موارد دیگر')], default='explosion', max_length=20)),
                ('subtask1_responsible', models.CharField(choices=[('رئیس بهره بردار', 'رئیس بهره برداری'), ('سرپرست نوبتکارا', 'سرپرست نوبتکاران'), ('نوبتکار ارشد', 'نوبتکار ارشد'), ('نوبتکار', 'نوبتکار')], default='2', max_length=20)),
                ('related_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.tasks')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name=' سوال مرتبط ')),
                ('correct_answer', models.TextField(verbose_name=' پاسخ صحیح ')),
                ('wrong_answer1', models.TextField(verbose_name=' گزینه غلط اول ')),
                ('wrong_answer2', models.TextField(verbose_name=' گزینه غلط دوم ')),
                ('wrong_answer3', models.TextField(verbose_name=' گزینه غلط سوم ')),
                ('related_subtask1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.subtasks1')),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.TextField(verbose_name=' تجربه مرتبط ')),
                ('documents', models.TextField(default='مدارک تجهیزات مرتبط', verbose_name=' مدارک مرتبط ')),
                ('property_score', models.IntegerField(choices=[(1, 'refered to process'), (2, 'refered to equipment manipulation'), (3, 'refered to human safty')], default=1)),
                ('experience_creator', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_subtask1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.subtasks1')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_point', models.IntegerField(default=0, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
