# Generated by Django 3.1.3 on 2021-06-15 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number_of_new_experiences',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_repeated_experiences',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_submitted_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='properties',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_score',
            field=models.IntegerField(choices=[(1, 'refered to process'), (2, 'refered to equipment manipulation'), (3, 'refered to human safty')], default=1),
        ),
        migrations.AddField(
            model_name='subtasks1',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subtasks1',
            name='property_score',
            field=models.IntegerField(choices=[(1, 'refered to process'), (2, 'refered to equipment manipulation'), (3, 'refered to human safty')], default=1),
        ),
        migrations.AddField(
            model_name='subtasks1',
            name='subtask1_creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasks',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_score',
            field=models.IntegerField(choices=[(1, 'refered to process'), (2, 'refered to equipment manipulation'), (3, 'refered to human safty')], default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_point',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='questions',
            name='related_subtask1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.subtasks1'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
