# Generated by Django 3.1.3 on 2021-06-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_auto_20210615_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_explaination',
            field=models.TextField(blank=True, null=True, verbose_name=' توضیحات مرتبط '),
        ),
    ]
