# Generated by Django 3.1.3 on 2021-06-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_questions_question_explaination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='number_of_submitted_questions',
            new_name='number_of_new_submitted_questions',
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_new_subtask1s',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_new_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_repeated_submitted_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_repeated_subtask1s',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_repeated_tasks',
            field=models.IntegerField(default=0),
        ),
    ]
