# Generated by Django 3.1.3 on 2021-06-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_auto_20210615_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtasks1',
            name='subtask1_name',
            field=models.CharField(default='زیروظیفه', max_length=264),
        ),
    ]
