# Generated by Django 3.1.3 on 2021-06-19 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_auto_20210615_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtasks1',
            name='number_of_related_experiences',
            field=models.IntegerField(default=0),
        ),
    ]
