# Generated by Django 3.1.3 on 2021-06-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0008_auto_20210619_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtasks1',
            old_name='number_of_related_experiences',
            new_name='number_of_submitted_experiences',
        ),
        migrations.AddField(
            model_name='subtasks1',
            name='number_of_verified_experiences',
            field=models.IntegerField(default=0),
        ),
    ]
