# Generated by Django 3.1.3 on 2021-06-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0009_auto_20210620_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='number_of_new_experiences',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number_of_new_submitted_questions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number_of_new_subtask1s',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number_of_new_tasks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number_of_repeated_experiences',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number_of_repeated_submitted_questions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number_of_repeated_subtask1s',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number_of_repeated_tasks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subtasks1',
            name='number_of_submitted_experiences',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subtasks1',
            name='number_of_verified_experiences',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
